# Generated by Django 6.0 on 2026-02-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nro_registro',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
