# Generated by Django 6.0 on 2026-01-18 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaciAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objetivo_general', models.TextField(null=True)),
                ('adecuacion_curricular', models.TextField(null=True)),
                ('estrategias', models.TextField(blank=True)),
                ('axis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci_axis', to='core.eje')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci_student', to='core.estudiante')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci_subject', to='core.asignatura')),
            ],
            options={
                'verbose_name': 'Paci App Model',
                'verbose_name_plural': 'Paci App Models',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=150, null=True)),
                ('paci', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_paci', to='paciApp.paciappmodel')),
            ],
        ),
    ]
