# Generated by Django 5.2.8 on 2025-11-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaciAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objetivo_general', models.TextField()),
                ('adecuacion_curricular', models.TextField()),
                ('estrategias', models.TextField(blank=True)),
                ('puntaje_total', models.SmallIntegerField(blank=True, null=True)),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paci_axis', to='core.eje')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paci_student', to='core.estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paci_subject', to='core.asignatura')),
            ],
            options={
                'verbose_name': 'Paci App Model',
                'verbose_name_plural': 'Paci App Models',
            },
        ),
    ]
