# Generated by Django 5.2.8 on 2025-11-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciappmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='paciappmodel',
            name='adecuacion_curricular',
        ),
        migrations.RemoveField(
            model_name='paciappmodel',
            name='axis',
        ),
        migrations.RemoveField(
            model_name='paciappmodel',
            name='estrategias',
        ),
        migrations.RemoveField(
            model_name='paciappmodel',
            name='objetivo_general',
        ),
        migrations.RemoveField(
            model_name='paciappmodel',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='paciappmodel',
            name='puntaje_total',
        ),
        migrations.RemoveField(
            model_name='paciappmodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='paciappmodel',
            name='subject',
        ),
    ]
