# Generated by Django 5.2.8 on 2025-11-14 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sala_teachers_sala_teachers'),
        ('paciApp', '0002_alter_paciappmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciappmodel',
            options={'verbose_name': 'Paci App Model', 'verbose_name_plural': 'Paci App Models'},
        ),
        migrations.AddField(
            model_name='paciappmodel',
            name='adecuacion_curricular',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paciappmodel',
            name='axis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci_axis', to='core.eje'),
        ),
        migrations.AddField(
            model_name='paciappmodel',
            name='estrategias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciappmodel',
            name='objetivo_general',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='paciappmodel',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciappmodel',
            name='puntaje_total',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paciappmodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci_student', to='core.estudiante'),
        ),
        migrations.AddField(
            model_name='paciappmodel',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci_subject', to='core.asignatura'),
        ),
    ]
