# Generated by Django 6.0 on 2026-01-18 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(blank=True, max_length=150)),
                ('profesional', models.CharField(blank=True, max_length=150)),
                ('objetivos_curriculares', models.TextField(blank=True)),
                ('objetivo_general', models.TextField(blank=True)),
                ('conocimientos', models.TextField(blank=True)),
                ('habilidades', models.TextField(blank=True)),
                ('actitudes', models.TextField(blank=True)),
                ('gantt_data', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('procedimiento', models.CharField(default='Observador', max_length=120)),
                ('instrumento', models.CharField(default='Escala de apreciacion', max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignaturas', models.ManyToManyField(related_name='proyectos_aula', to='core.asignatura')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_aula', to='core.sala')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoSubsector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_gantt', models.TextField(blank=True)),
                ('acciones', models.TextField(blank=True)),
                ('fechas', models.TextField(blank=True)),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_aula', to='core.eje')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsectores', to='aula.proyectoaula')),
            ],
            options={
                'unique_together': {('proyecto', 'eje')},
            },
        ),
    ]
