# Generated by Django 5.2.8 on 2025-11-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosubsector',
            name='acciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyectosubsector',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
