# Generated by Django 5.2.8 on 2025-11-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_proyectosubsector_acciones_proyectosubsector_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectosubsector',
            name='fecha',
        ),
        migrations.AddField(
            model_name='proyectosubsector',
            name='fechas',
            field=models.TextField(blank=True),
        ),
    ]
