# Generated by Django 5.2.8 on 2025-11-11 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('ocupation', models.CharField(max_length=20)),
                ('collage_level', models.CharField(choices=[('Básico Completo', 'Básico Completo'), ('Básico Incompleto', 'Básico Incompleto'), ('Medio Completo', 'Medio Completo'), ('Medio Incompleto', 'Medio Incompleto'), ('Superior', 'Superior')], default='Básico Completo', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('BASICO', 'Básico'), ('LABORAL', 'Laboral')], default='BASICO', max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('teachers', models.ManyToManyField(blank=True, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejes', to='core.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='core.eje')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('bapDiag', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('commune', models.CharField(max_length=40)),
                ('etnia', models.CharField(blank=True, max_length=40, null=True)),
                ('nivel', models.CharField(choices=[('BASICO', 'Básico'), ('LABORAL', 'Laboral')], default='BASICO', max_length=10)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.curso')),
                ('parents', models.ManyToManyField(blank=True, related_name='students', to='core.apoderado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
