# Generated by Django 6.0 on 2026-02-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='teachers',
        ),
    ]
