# Generated by Django 5.2.8 on 2025-11-14 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='sala',
            new_name='nombre_sala',
        ),
        migrations.AddField(
            model_name='curso',
            name='sala_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='core.sala'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='profesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
