# Generated by Django 6.0 on 2026-02-11 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sala_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sala_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='core.sala'),
        ),
    ]
