# Generated by Django 5.2.8 on 2025-11-14 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_sala_sala_nombre_sala_curso_sala_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='teachers',
        ),
        migrations.AddField(
            model_name='sala',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='profesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
