# Generated by Django 6.0 on 2026-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_curso_sala_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(max_length=10, unique=True, verbose_name='RUT'),
        ),
    ]
