# Generated by Django 5.2.8 on 2025-11-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sala_teachers_sala_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(max_length=100)),
            ],
        ),
    ]
