# Generated by Django 5.2.8 on 2025-11-19 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_sala_teachers_sala_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=150, null=True)),
                ('puntaje', models.SmallIntegerField(blank=True, null=True)),
                ('puntaje_obtenido', models.SmallIntegerField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci', to='core.asignatura')),
            ],
        ),
    ]
