# Generated by Django 6.0 on 2026-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores_instrumento',
            name='adecuacion_curricular',
            field=models.TextField(null=True),
        ),
    ]
