# Generated by Django 6.0 on 2025-12-30 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentosApp', '0002_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicador_nota', to='instrumentosApp.indicadores'),
        ),
    ]
