# Generated by Django 6.0 on 2026-01-31 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instrumentosApp', '0002_indicadores_instrumento_adecuacion_curricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adecuacion_curricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adecuacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicadores_instrumento',
            name='adecuacion_curricular',
        ),
        migrations.RemoveField(
            model_name='indicadores_instrumento',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='indicadores_instrumento',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='indicador',
        ),
        migrations.AlterField(
            model_name='indicadores_instrumento',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.asignatura'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota', to='core.asignatura'),
        ),
        migrations.CreateModel(
            name='Instrumento_evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adecuaciones', models.ManyToManyField(blank=True, related_name='instrumento', to='instrumentosApp.adecuacion_curricular')),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrumento', to='core.estudiante')),
                ('nota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrumento', to='instrumentosApp.nota')),
            ],
        ),
        migrations.AddField(
            model_name='indicadores_instrumento',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='instrumentosApp.instrumento_evaluacion'),
        ),
    ]
