# Generated by Django 6.0 on 2026-01-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentosApp', '0003_nota_indicador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
