# Generated by Django 6.0 on 2026-01-31 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentosApp', '0003_adecuacion_curricular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento_evaluacion',
            name='adecuaciones',
        ),
        migrations.AddField(
            model_name='adecuacion_curricular',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adecuaciones', to='instrumentosApp.instrumento_evaluacion'),
        ),
    ]
