# Generated by Django 6.0 on 2026-01-31 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentosApp', '0004_remove_instrumento_evaluacion_adecuaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento_evaluacion',
            name='nota',
        ),
        migrations.AddField(
            model_name='nota',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='instrumentosApp.instrumento_evaluacion'),
        ),
    ]
