# Generated by Django 6.0 on 2026-03-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentosApp', '0005_remove_instrumento_evaluacion_nota_nota_instrumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento_evaluacion',
            name='numero_evaluacion',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
