# Generated by Django 6.0 on 2026-01-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentosApp', '0007_nota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
