# Generated by Django 5.2.8 on 2025-11-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.CharField(max_length=150)),
                ('puntaje', models.SmallIntegerField(blank=True, null=True)),
                ('puntaje_obtenido', models.SmallIntegerField(blank=True, null=True)),
                ('paci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci', to='paciApp.paciappmodel')),
            ],
        ),
    ]
