# Generated by Django 5.2.8 on 2025-11-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadoresApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadores',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='indicadores',
            name='paci',
        ),
        migrations.RemoveField(
            model_name='indicadores',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='indicadores',
            name='puntaje_obtenido',
        ),
    ]
