# Generated by Django 5.2.8 on 2025-11-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadoresApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadores',
            name='puntaje',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicadores',
            name='puntaje_obtenido',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
