# Generated by Django 5.2.8 on 2025-11-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadoresApp', '0002_remove_indicadores_indicador_remove_indicadores_paci_and_more'),
        ('paciApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='indicador',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='indicadores',
            name='paci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paci', to='paciApp.paciappmodel'),
        ),
        migrations.AddField(
            model_name='indicadores',
            name='puntaje',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadores',
            name='puntaje_obtenido',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
