# Generated by Django 6.0 on 2026-01-18 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PlanEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_general', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_evaluacion', to='core.curso')),
                ('decreto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='ped.decreto')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimiento', models.TextField(blank=True)),
                ('instrumento', models.TextField(blank=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_evaluacion', to='core.asignatura')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_asignaturas', to='ped.planevaluacion')),
            ],
            options={
                'unique_together': {('plan', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='ObjetivoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('objAsignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_generales', to='core.asignatura')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_generales', to='ped.planevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='core.eje')),
                ('plan_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_ejes', to='ped.planasignatura')),
            ],
            options={
                'unique_together': {('plan_asignatura', 'eje')},
            },
        ),
    ]
