# Generated by Django 5.2.8 on 2025-11-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_asignatura_objetivo_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('objAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_generales', to='core.asignatura')),
            ],
        ),
    ]
