# Generated by Django 5.2.8 on 2025-11-13 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ped', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planevaluacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_evaluacion', to='core.curso'),
        ),
    ]
